### ISSUE TITLE
ReactUI keyboard shortcuts won't refresh UI

### ISSUE THREAD

**Issue by jbalsas** [liferay/alloy-editor#141]
In ReactUI, when executing commands via keyboard shortcuts, the UI doesn't refresh immediately.

__Steps to reproduce:__
1.- Select a text
2.- Click CMD(CTRL) + B to make it bold
3.- Don't release the CMD(CTRL) key (edited)

__Expected:__
The text to become bold and the bold button to become active

__Actual result:__
The text becomes bold but the button remains inactive

**Comment by ipeychev** [comment]
Fixed

**Comment by jbalsas** [comment]
Hey Iliyan, as far as I know, this is not yet fixed.

You need to release the key CMD (or CTRL) key in order to see the UI render again, which doesn't really feel right. It's a minor UX issue, but still pressent.

**Comment by ipeychev** [comment]
Okay, reopening

**Comment by jbalsas** [comment]
This can be fixed using the new `keystroke` feature asked for in #417
