### ISSUE TITLE
Resize arrows still appearing after disabling the drag resize on Firefox

### ISSUE THREAD

**Issue by omarzzn3** [liferay/alloy-editor#755]
Reproduction steps: 
1. Add **config.removePlugins = "ae_dragresize"** to the config.js file 
2. Start the demo on Firefox browser
Expected behavior: 
No drag resize arrows visible 
Actual behavior:
The drag resize arrows are still appearing

The Firefox browser adds **_moz_resizing="true"** attribute to the img tag in the HTML code automatically and this may be the cause of the issue

**Comment by ipeychev** [comment]
Hey @omarzzn3,

Fixed. Also, better use this way for removing plugins, since by default there are other plugins removed:
```
removePlugins: AlloyEditor.Core.ATTRS.removePlugins.value +
    ',ae_dragresize'
```

Thanks,

**Comment by omarzzn3** [comment]
Hey @ipeychev, 

I tried your solution after building the source and setting **config.removePlugins = 'ae_dragresize'** and the issue is still reproducible.

Also, would you please clarify where the mentioned portion of code should be set?
`removePlugins: AlloyEditor.Core.ATTRS.removePlugins.value +
    ',ae_dragresize'` 

Thank you and best regards,
Omar

**Comment by ipeychev** [comment]
Hey @omarzzn3,

`removePlugins: AlloyEditor.Core.ATTRS.removePlugins.value + ',ae_dragresize'` has to be set in the config of AlloyEditor, like this:
```javascript
var editor2 = AlloyEditor.editable('editable', {
    // other config options here
    removePlugins: AlloyEditor.Core.ATTRS.removePlugins.value + ',ae_dragresize'
});
```
Please set this and try again.
